### ISSUE TITLE
Batch upload button doesn't come up

### ISSUE THREAD

**Issue by renier** [spanner/radiant-paperclipped_uploader-extension#5]
Installed the uploader extension on radiant 0.9.1 and ran migrations and update. But I can't find the batchupload button anywhere. Could I get some tips on debugging this? Thanks.

**Comment by renier** [comment]
By looking at the extension code, found that the form is at /admin/assets/uploader. Would be nice to add a link to this from the assets page.

**Comment by spanner** [comment]
It should be there now both with the stock paperclipped and with my (now short-lived) fork.
